[package]
name = "query_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
buffer_pool_manager = { path = "../buffer-pool-manager" }
storage_engine = { path = "../storage-engine" }

[dev-dependencies]
