[package]
name = "benchmarking"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
concurrent = { path = "../concurrent" }
actor = { path = "../actor" }
clap = { version = "4.0", features = ["derive"] }